### ISSUE TITLE
Current issues!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [EPIICTHUNDERCAT/Raft-Mod#1]
Separator Recipes don't work
Entities crash when killed by other methods
Tree Spawning glitch

Will add more as we go

**Comment by Wqrld** [comment]
i suggest you remove glitches instead of adding them ;)

**Comment by EPIICTHUNDERCAT** [comment]
what lol? @aycgit

**Comment by EPIICTHUNDERCAT** [comment]
this is all fixed***

**Comment by Wqrld** [comment]
i was just joking

**Comment by EPIICTHUNDERCAT** [comment]
i know haha, howd you find this? @aycgit

**Comment by Wqrld** [comment]
it was in my feed because sekwah41 forked it
